





# Stop GNU make from overzealous deletion of intermediate files
#.PRECIOUS: %.dvi %.ps %.pdf
.SECONDARY:



# Copy the pstree generated by Excel to a text file 'psbaum.tex' ---

# 'soffice' is a command-line tool to convert from LibreOffice to textfile.
soffice := soffice --headless --convert-to csv:"Text - txt - csv (StarCalc)":59,ANSI,0 

# The bit 1 (or 2) >/dev/null at end of line will suppress printing to the terminal.
build/generator.csv: generator.xls
	@$(soffice) $< 1>/dev/null 2>/dev/null
	@mv generator.csv $@

# Next extract the LaTeX pstree to file 'psbaum.tex'
# and then delete all occurrences of ';' via 
# 	sed -e 's/;//g' $@
build/psbaum.tex: build/generator.csv
	@sed -n '10,12p;12q' $< | \
	sed -e 's/;//g' > $@


# Engine :
TX:= latex

# Logfile :
LOG:= build/compile.log

build/baum.dvi: build/baum.tex build/psbaum.tex
	@#echo "Running LaTeX on input file (compilation log in $(LOG))..."
	@#echo "\t $(TX) -output-directory=build $<"
	@$(TX) -interaction=batchmode -output-directory=build $< > $(LOG) 2>&1

build/%.ps: build/%.dvi $(epsfiles)
	@#echo "Converting $< to Postscript..."
	@dvips -o $@ $< >> $(LOG) 2>&1

build/%.pdf: build/%.ps
	@#echo "Converting $< to PDF..."
	@#ps2pdf $< $@ >> $(LOG) 2>&1 # disable the ps2pdf wrapper
	@gs -dSafer -sDEVICE=pdfwrite -dALLOWPSTRANSPARENCY -sPAPERSIZE=a4 -dPSFitPage -dFIXEDMEDIA -o $@ -f $< >> $(LOG) 2>&1



.PHONY: clean pdf

out_baum.pdf: build/baum.pdf
	@mv $< $@

pdf: out_baum.pdf

clean: 
	@rm -f build/psbaum.tex

	@rm -f build/baum.aux
	@#rm -f build/baum.tex  keep this!
	@rm -f build/baum.dvi
	@rm -f build/baum.ps
	@rm -f build/baum.pdf
	@rm -f   out_baum.pdf

	@rm -f build/baum.log
	@rm -f build/compile.log
	@rm -f build/generator.csv






# This is the content of file "build/baum.tex"


#    \documentclass[12pt]{article}
#    \usepackage[ansinew]{inputenc}
#    \usepackage{pst-tree}
#    \usepackage[a4paper, margin=5mm, top=25mm, left=25mm]{geometry}
#    
#    \begin{document}
#    \input{build/psbaum.tex}
#    \end{document}

# End of file baum.tex .
